# Generated by Django 2.0.7 on 2018-09-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_templates', '0001_initial'),
        ('list_based_flavorpack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbasedregion',
            name='template',
            field=models.ForeignKey(help_text='The Django/Jinja template to send a formatted request for number ranges', null=True, on_delete=django.db.models.deletion.PROTECT, to='quartet_templates.Template', verbose_name='Message Template'),
        ),
    ]
