# Generated by Django 2.1.1 on 2018-09-21 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('list_based_flavorpack', '0003_auto_20180920_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbasedregion',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
