# Generated by Django 2.1.1 on 2018-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_based_flavorpack', '0004_listbasedregion_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbasedregion',
            name='directory_path',
            field=models.CharField(blank=True, default='/var/quartet/numbers', help_text='The full path to the directory where numbers will be stored.Leave blank for default. Default is /var/quartet/numbers', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='listbasedregion',
            name='number_replenishment_size',
            field=models.IntegerField(default=20, help_text='The size that the outbound message will request from the third-party system,if numbers available are low. E.g.: 500', verbose_name='Number Replenishment Size'),
            preserve_default=False,
        ),
    ]
