# Generated by Django 3.1.1 on 2020-09-29 21:30

from django.db import migrations, models
import list_based_flavorpack.models


class Migration(migrations.Migration):

    dependencies = [
        ('list_based_flavorpack', '0008_auto_20200401_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbasedregion',
            name='database_name',
            field=models.CharField(blank=True, default=list_based_flavorpack.models.haikunate, help_text='The name of the database file if this is a database range.', max_length=50, null=True, unique=True, verbose_name='Database File'),
        ),
    ]
