# Generated by Django 3.1.4 on 2021-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_based_flavorpack', '0009_auto_20200929_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listbasedregion',
            name='database_name',
            field=models.CharField(blank=True, help_text='The name of the database file if this is a database range.', max_length=50, null=True, unique=True, verbose_name='Database File'),
        ),
    ]
